version: '3.9'

services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabaseAWS
      MYSQL_USER: myuserAWS
      MYSQL_PASSWORD: mypasswordAWS
      

  web:
    build: .
    command: sh -c "sleep 10 && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=mydatabaseAWS
      - DB_USER=myuserAWS
      - DB_PASSWORD=mypasswordAWS
      - DB_PORT=3306
    depends_on:
      - db

volumes:
  mysql_data:
